apiVersion: v1
kind: Service
metadata:
  name: flask-redis-service
  labels:
    app: flask-redis
spec:
  type: NodePort
  selector:
      app: flask-redis
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30080